# Generated by Django 3.2.19 on 2023-11-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_currency',
        ),
    ]
