# Generated by Django 3.2.19 on 2023-11-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image_url',
        ),
    ]
