# Generated by Django 3.2.19 on 2023-11-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20231130_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='newsletter',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (3, 'Subscribe to newsletter')], default=3),
        ),
    ]
