# Generated by Django 3.2.19 on 2023-11-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_userprofile_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_currency',
            field=models.IntegerField(choices=[(0, 'USD'), (1, 'SEK'), (2, 'GBP'), (3, 'EUR')], default='USD'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='newsletter',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
