# Generated by Django 3.2.19 on 2023-11-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20231130_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_currency',
            field=models.IntegerField(choices=[(0, 'USD'), (1, 'SEK'), (2, 'GBP'), (3, 'EUR')], default=0),
        ),
    ]
