# Generated by Django 3.2.19 on 2023-11-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_userprofile_default_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
