# Generated by Django 3.2.19 on 2023-11-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_userprofile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
