# Generated by Django 3.2.19 on 2023-11-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_userprofile_default_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.IntegerField(choices=[(0, 'USD'), (1, 'SEK')], default=0),
        ),
    ]
