# Generated by Django 3.2.19 on 2023-11-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_userprofile_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_currency',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.IntegerField(choices=[(0, 'USD'), (1, 'SEK'), (2, 'GBP'), (3, 'EUR')], default=0),
        ),
    ]
