# Generated by Django 3.2.19 on 2023-11-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20231130_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='newsletter',
        ),
    ]
