# Generated by Django 3.2.19 on 2023-11-02 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
