# Generated by Django 3.2.19 on 2023-11-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20231102_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
