# Generated by Django 3.2.19 on 2023-11-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newsfeed_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfeed',
            name='url',
        ),
    ]
