# Generated by Django 3.2.19 on 2023-11-03 22:11

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_newsfeed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('friendly_name', models.CharField(max_length=40, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('description', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['friendly_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['friendly_name']},
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='short_name',
            new_name='friendly_name',
        ),
    ]
