# Generated by Django 3.2.19 on 2023-11-03 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20231103_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediatype',
            name='description',
        ),
    ]
