# Generated by Django 3.2.19 on 2023-11-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_mediatype_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='genre',
        ),
    ]
