# Generated by Django 3.2.19 on 2023-11-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mediatype',
        ),
    ]
