# Generated by Django 3.2.19 on 2023-11-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_mediatype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='artist',
        ),
    ]
