# Generated by Django 3.2.19 on 2023-11-12 22:48

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=200)),
                ('subjectline', models.CharField(max_length=200)),
                ('user_message', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
