# Generated by Django 3.2.19 on 2023-11-12 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contact_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_messages',
            new_name='contact_message',
        ),
    ]
