# Generated by Django 3.2.19 on 2023-11-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_contact_messages_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_message',
            name='complete',
            field=models.IntegerField(choices=[(0, 'Not complete'), (1, 'Completed')], default=0),
        ),
    ]
