# Generated by Django 3.2.19 on 2023-11-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='prod',
            new_name='product',
        ),
    ]
