# Generated by Django 3.2.19 on 2023-11-04 13:21

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_mediatype'),
    ]

    operations = [
        migrations.CreateModel(
            name='artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='friendly_name', unique=True)),
                ('description', models.CharField(max_length=200)),
                ('artist_image', models.CharField(default='empty-artist-image.png', max_length=60)),
            ],
            options={
                'ordering': ['friendly_name'],
            },
        ),
    ]
