# Generated by Django 3.2.19 on 2023-11-04 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='media_color',
            field=models.IntegerField(choices=[(0, 'Black'), (1, 'Gold'), (2, 'Red'), (3, 'Green'), (4, 'Picture'), (5, 'Transparant'), (6, 'Blue')], default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='media_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.genre'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_old',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Second hand')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.mediatype'),
        ),
    ]
