# Generated by Django 3.2.19 on 2023-11-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20231104_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.artist'),
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.genre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='media_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.mediatype'),
        ),
    ]
