# Generated by Django 3.2.19 on 2023-11-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20231104_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist_image',
        ),
    ]
