# Generated by Django 3.2.19 on 2023-11-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=1, null=True),
        ),
    ]
