# Generated by Django 3.2.19 on 2023-12-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='prod_testimonial',
            new_name='reviewed',
        ),
    ]
