# Generated by Django 3.2.19 on 2023-12-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_reviewed_testimonial_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='testint',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
