# Generated by Django 3.2.19 on 2023-12-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_testint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='testint',
        ),
    ]
